### ISSUE TITLE
Interop with python

### ISSUE THREAD

**Issue by avaranovich** [djspiewak/cccp#20]
Hi there,

I am trying to integrate cccp agent with python, basically I open socket and send SExpr as strings

From the client side:
1. Open the socket
2. Send: 000056(:swank-rpc (swank:init-connection (:protocol "http" :host "localhost" :port 8585)) 1)
3. Send: 000031(:swank-rpc (swank:link-file "log" "test.txt") 2)
4. Close the socket

That is what I see in the "agent" log:
Handling chunk: (:swank-rpc (swank:init-connection (:protocol "http" :host "localhost" :port 8585)) 1)
Handling chunk: (:swank-rpc (swank:link-file "log" "test.txt") 2)
ERROR!!!  NumberFormatException: java.lang.NumberFormatException: For input string: ""
Initializing connection: http://localhost:8585

Any ideas what's wrong with the second request?

UPDATE:
I realized that it happens even I send one request and then _close_ the client socket.
Handling chunk: (:swank-rpc (swank:init-connection (:protocol "http" :host "localhost" :port 8585)) 1)
ERROR!!!  NumberFormatException: java.lang.NumberFormatException: For input string: ""
Initializing connection: http://localhost:8585

**Comment by djspiewak** [comment]
The problem with the second request is the input length.  Specifically, you have specified a length of `000060`, which is decimal 96.  This is a problem, because the actual chunk, `(:swank-rpc (swank:link-file "log" "test.txt") 2)`, is only 49 bytes long.  Thus, the agent reader gets quite a bit off, resulting in the `NumberFormatException`.  The error could probably be clearer, but obviously handling malformed protocol chunks is a tricky problem.
